language: csharp
mono: none
dotnet: 3.1
dist: xenial
solution: IpcServiceFramework.sln
install:
 - cd ./src
 - dotnet restore
script:
 - cd ./src
 - dotnet restore
 - dotnet build --configuration Release
 - dotnet test JKang.IpcServiceFramework.Core.Tests
